name: Deploy Frontend Infra and Code

on:
    push:
        branches:
            - main
    workflow_dispatch:
        inputs:
            environment:
                description: 'Target environment (dev1, dev, stg, prod)'
                required: true
                default: 'dev1' # Default value, adjust as needed
                type: choice
                options:
                    - dev1
                    - dev
                    - staging
                    - prod

permissions:
    id-token: write # May be needed by azure/login internally
    contents: read  # To checkout the code

jobs:
    get-changes:
        runs-on: ubuntu-latest
        outputs:
            infra_frontend_bicep: ${{ steps.get-changes.outputs.infra_frontend_bicep }}
            ui_frontend_code: ${{ steps.get-changes.outputs.ui_frontend_code }}
        steps:
            - uses: actions/checkout@v4
            - uses: dorny/paths-filter@v3
              id: get-changes
              with:
                filters: |
                    infra_frontend_bicep:
                      - 'infra/staticWebApp/**'
                    ui_frontend_code:
                      - 'frontend/**'

                    
    deploy-infra:
        if: ${{ needs.get-changes.outputs.infra_frontend_bicep == 'true' || github.event_name == 'workflow_dispatch' }} # Only runs if changes in infra are detected or manually triggered
        needs: get-changes
        uses: ./.github/workflows/deploy-frontend-infra.yml
        with:
          environment: ${{ github.event.inputs.environment || 'dev1' }}
        secrets: inherit

    deploy-ui-code:
        needs: 
            - get-changes
            - deploy-infra
        if: ${{ (needs.get-changes.outputs.ui_frontend_code == 'true' || github.event_name == 'workflow_dispatch') && (success() || needs.deploy-infra.result == 'skipped' )}}
        uses: ./.github/workflows/deploy-ui-code.yml
        with:
            environment: ${{ github.event.inputs.environment || 'dev1' }}
        secrets: inherit

